#https://www.linkedin.com/pulse/create-angular-app-using-deploy-aws-suite-andr%C3%A9s-casta%C3%B1o/
version: 0.2
environment_variables:
  plaintext:
    S3_BUCKET: "www.beinghealer.com"
    BUILD_ENV: "prod"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli@13.3.0
      - npm install -g gzipper
  build:
    commands:
      - echo Build started on `date`
      - ng build --aot --configuration=production --build-optimizer
      - npm run gzipper-dist
#      Above command will be picked from package.json. It will gzip dist files to beinghealer-gzip dist folder and sync the zip folder to s3 while setting content-encoding = gzip abd keeping file name and extension same as before.
  #Such gzip files if have content-encoding as gzip, and file extension as js, css, jpg, png, etc, then browser renders them based on content-type, but in the process we save a lot in size by doing file compression
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - aws s3 rm s3://www.beinghealer.com --recursive --region ap-south-1
      - aws s3 sync dist/beinghealer-gzip s3://www.beinghealer.com --delete --content-encoding=gzip --region ap-south-1
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/beinghealer'
  discard-paths: yes
